CREATE DATABASE IF NOT EXISTS alkemy_ong;
USE alkemy_ong;

CREATE TABLE IF NOT EXISTS testimonials (
id BIGINT(255) NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (255) NOT NULL,
image VARCHAR (255),
content VARCHAR (255),
created TIMESTAMP DEFAULT NOW(),
updated TIMESTAMP,
deleted TINYINT(1)
);